### ISSUE TITLE
sevctl build fail

### ISSUE THREAD

**Issue by MoeMahhouk** [enarx-archive/sevctl#44]
Hello there,

i was trying to check your Enarx project on an AMD server but the compilation process fails because a macro definition was not found.
Here is the associated error message:

> error: cannot find macro `matches` in this scope
>    --> /.cargo/git/checkouts/sev-5761dc29700bd37c/3a32c93/src/certs/sev/cert/v1/sig/mod.rs:153:18
>     |
> 153 |                 !matches!(
>     |                  ^^^^^^^
> 
> error: aborting due to previous error
> 
> error: could not compile `sev`.

am i missing something or doing something wrong here?

Thanks for your help in advance

**Comment by connorkuehl** [comment]
Hi @MoeMahhouk -- your toolchain might be too old. The `matches!` macro was introduced in Rust 1.42.0. Could you confirm your toolchain is newer than that?

```console
$ cargo --version
$ rustc --version
```

**Comment by MoeMahhouk** [comment]
oh yeah that solved it, thanks a lot @connorkuehl
